name: Deploy API to VPS

# CI/CD ini akan berjalan otomatis jika ada kode baru yang di-push ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Menjalankan Perintah di VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # Perintah di bawah ini akan dijalankan di dalam VPS Anda.
          # (Pastikan Anda sudah mengubah nama folder 'product-categorization'
          # jika di VPS nama foldernya berbeda).
          script: |
            cd ~/product-categorization
            git pull origin main
            docker compose up -d --build
